### PR TITLE
Implement 2fa authentication

### PR DESCRIPTION
**Pull request by Yuerino**

### CODE REVIEW

**Comment by dejanzivanov** [comment]
How to:

- Visit: http://localhost:8080/login
- Visit: http://localhost:8080/2fa/generate
You will get the picture of the Quar code, scan it with your Google Authenticator Application(application has option 'Scan Quar Code')
- Visit: http://localhost:8080/2fa/enable?code=<INSERT THE CODE HERE FROM YOUR AUTHENTICATION APPLICATION>
For example: http://localhost:8080/2fa/enable?code=664128

The result should be the following: 

image

If you get the false, delete the item with the word of our project, and try follwing the steps from the beginning again.

TODO:
- Connect with frontend when its done.
- Login is not connected 2FA(new issue) #93 

Email of the user is inside JWT token

**Comment by Yuerino** [comment]
Suspend due to #94 while merging

**Comment by Yuerino** [comment]
While merging, I updated the update2FASecret and update2FAEnable in UsersService to throw QueryFailedError in case we update nonexisting user and handle those error correctly in the 2FA Controllers

**Comment by GQDeltex** [comment]
Two things:
- [ ] There is no protection against re-generating your secret, which invalidates the code you saved (but still leaves enabled=true).
- [ ] TOTP is not actually checked when logging in (at least I wasn't asked for my 2fa token on login)

So my question would be, are those things still in the scope of this Issue/PR or should we create new issues?

**Review by GQDeltex — APPROVED** [review]
Aside from mentioned points, this looks great.

**Comment by Yuerino** [comment]
> Two things:
> 
>     * [ ]  There is no protection against re-generating your secret, which invalidates the code you saved (but still leaves enabled=true).
> 
>     * [ ]  TOTP is not actually checked when logging in (at least I wasn't asked for my 2fa token on login) ([Connect login with the 2FA system #93](https://github.com/GQDeltex/ft_transcendence/issues/93))
> 
> 
> So my question would be, are those things still in the scope of this Issue/PR or should we create new issues?
> 
> Edit: Just saw there is already an issue for one of the points, (See [#91 (comment)](https://github.com/GQDeltex/ft_transcendence/pull/91#issuecomment-1271827633) and #93 )

We still haven't decided on the authentication flow and how to integrate this with JWT and guard we have currently. Right now with this PR although we can generate 2FA but it is not used for anything but we decided this PR is done for now and we will split the rest into new issue to avoid long running PR.

**Pull request merged**
