### PR TITLE
implement friendship system on backend

### PR DESCRIPTION
**Pull request by Yuerino**
### User entity
- 2 new column following and followers as a user array type to keep track friendship
- these 2 column are ManyToMany (user to user) relationship
- following is a list of user you follow and inversely bind to the followed user followers column
- followers is a list of user that followed you and inversely bind to the followed user following column

### User GraphQL
- new graphql mutation to add/remove/accept/decline/cancel friend
- new fields for User type: `friends`, `sentFriendRequests`, `receivedFriendRequests`
- those fields are `ResolveField` and will return accordingly by filtering out from the following and followers column

### Limitation
- overhead of keeping track of 2 column with duplicating value
- no metadata of friendship (example: timestamp when both are friends)

But this is the easier way to do it without having to create and store a new separated entity

### Others
- right now `UsersService.find` and `findAll` will always query with relations which can be an overhead if we don't need them
- no test for the friendship system yet (haven't found an elegant way to do this because of the database relations)
- add mock user factory

### CODE REVIEW

**Review by GQDeltex — APPROVED** [review]
In general I like what you've done. I don't really like the computation intensive queries though. On the other hand they only get executed when you ask for them...
The other option would've been to store friend requests in a different table and then only have the friends relation in the user. That would keep the temporary stuff (requests) and the permanent (friends) a bit more separated. But this works, so :heavy_check_mark:

**Comment by GQDeltex** [comment]
@Yuerino You do know that you re-throw or don't catch some of the Errors?
```
backend_1   | [Nest] 41  - 10/19/2022, 2:15:53 PM   ERROR [ExceptionsHandler] Failed to cancel friend request
backend_1   | Error: Failed to cancel friend request
backend_1   |     at UsersService.updateFriendship (/app/src/users/users.service.ts:188:15)
backend_1   |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
backend_1   |     at UsersResolver.updateFriendship (/app/src/users/users.resolver.ts:85:5)
backend_1   |     at target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
backend_1   |     at Object.updateFriendship (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

**Comment by Yuerino** [comment]
> @Yuerino You do know that you re-throw or don't catch some of the Errors?
> 
> ```
> backend_1   | [Nest] 41  - 10/19/2022, 2:15:53 PM   ERROR [ExceptionsHandler] Failed to cancel friend request
> backend_1   | Error: Failed to cancel friend request
> backend_1   |     at UsersService.updateFriendship (/app/src/users/users.service.ts:188:15)
> backend_1   |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> backend_1   |     at UsersResolver.updateFriendship (/app/src/users/users.resolver.ts:85:5)
> backend_1   |     at target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
> backend_1   |     at Object.updateFriendship (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
> ```

Yes I was having this but it should not be there anymore with [9a59610](https://github.com/GQDeltex/ft_transcendence/pull/174/commits/9a596107b395a9bc0f79d7f9eda3dba50a7e04ea) and I can't reproduce the error on my side also. Have you updated the branch?

But basically what I've done is I change from throwing basic Error to ApolloError (UserInputError), which will display in graphql correctly but for some reason NestJS still logs the error out to the terminal. I believe this is NestJS related bugs, could be related to [#2060](https://github.com/nestjs/graphql/issues/2060) hence the purpose of the `AllExceptionFilter`

**Comment by Yuerino** [comment]
> In general I like what you've done. I don't really like the computation intensive queries though. On the other hand they only get executed when you ask for them... The other option would've been to store friend requests in a different table and then only have the friends relation in the user. That would keep the temporary stuff (requests) and the permanent (friends) a bit more separated. But this works, so ✔️

Yes there is indeed the limitation of this approach . The better option is definitely storing the friendship as separated entity and have it as user relations as you mentioned but for the time being I think this option will be fine and we can optimize it later on

**Comment by GQDeltex** [comment]
> > In general I like what you've done. I don't really like the computation intensive queries though. On the other hand they only get executed when you ask for them... The other option would've been to store friend requests in a different table and then only have the friends relation in the user. That would keep the temporary stuff (requests) and the permanent (friends) a bit more separated. But this works, so heavy_check_mark
> 
> Yes there is indeed the limitation of this approach . The better option is definitely storing the friendship as separated entity and have it as user relations as you mentioned but for the time being I think this option will be fine and we can optimize it later on

I actually meant to just store the friend-**request** in a separate table and have the friends still as many-to-many in the user. That would make querying and adding/removing friend requests easier

**Comment by GQDeltex** [comment]
> > @Yuerino You do know that you re-throw or don't catch some of the Errors?
> > ```
> > backend_1   | [Nest] 41  - 10/19/2022, 2:15:53 PM   ERROR [ExceptionsHandler] Failed to cancel friend request
> > backend_1   | Error: Failed to cancel friend request
> > backend_1   |     at UsersService.updateFriendship (/app/src/users/users.service.ts:188:15)
> > backend_1   |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> > backend_1   |     at UsersResolver.updateFriendship (/app/src/users/users.resolver.ts:85:5)
> > backend_1   |     at target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
> > backend_1   |     at Object.updateFriendship (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
> > ```
> 
> Yes I was having this but it should not be there anymore with [9a59610](https://github.com/GQDeltex/ft_transcendence/pull/174/commits/9a596107b395a9bc0f79d7f9eda3dba50a7e04ea) and I can't reproduce the error on my side anymore. Have you updated the branch?
> 
> But basically what I've done is I change from throwing basic Error to ApolloError (UserInputError), which will display in graphql correctly but for some reason NestJS still logs the error out to the terminal. I believe this is NestJS related bugs, could be related to [#2060](https://github.com/nestjs/graphql/issues/2060) hence the purpose of the `AllExceptionFilter`

Yes. Seems like I had an older version (for some reason?). Cannot reproduce either. Looks fine :+1:

**Review by hennneh — APPROVED** [review]
Thanks for explaining the testing procedure :) well done!

**Pull request merged**
