### PR TITLE
update profile picture fixed and tested - with nice french guy

### PR DESCRIPTION
**Pull request by Kromolux**

### CODE REVIEW

**Comment by GQDeltex** [comment]
I was writing test for the graphql endpoints and I discovered a deeper Problem with our code. If we run the update command on the database repository, we don't get an error back if the user id doesn't exist. That's because it just run a SQL `UPDATE ... WHERE id=...`, which is not wrong if the id doesn't exist, it just doesn't update anything. Due to this, if you run a graphql mutation to change e.g. the username, you just get `null` back, because the find one fails (my PR with the errors for that isn't merged yet #86). I don't think this is the behavior we want. Due to that fact, we might want to rework the users service for updating things a bit, where we could incorporate the asking for the updated data directly.

**Review by Yuerino — APPROVED** [review]
LGTM

**Comment by Yuerino** [comment]
> I was writing test for the graphql endpoints and I discovered a deeper problem with our code. If we run the update command on the database repository, we don't get an error back if the user id doesn't exist. That's because it just run a SQL `UPDATE ... WHERE id=...`, which is not wrong if the id doesn't exist, it just doesn't update anything. Due to this, if you run a graphql mutation to change e.g. the username, you just get `null` back, because the find one fails (my PR with the errors for that isn't merged yet #86). I don't think this is the behavior we want. Due to that fact, we might want to rework the users service for updating things a bit, where we could incorporate the asking for the updated data directly. Which in turn would mean we would have to update the users resolver too.

@GQDeltex update return UpdateResult type which has affected (how many rows/documents affected) so maybe we use that to check? It also has raw (raw SQL result) which possibly contains the whole user objects so we may not need to do another find call to DB.
```ts
/**
 * Result object returned by UpdateQueryBuilder execution.
 */
export declare class UpdateResult {
    static from(queryResult: QueryResult): UpdateResult;
    /**
     * Raw SQL result returned by executed query.
     */
    raw: any;
    /**
     * Number of affected rows/documents
     * Not all drivers support this
     */
    affected?: number;
    /**
     * Contains inserted entity id.
     * Has entity-like structure (not just column database name and values).
     */
    /**
     * Generated values returned by a database.
     * Has entity-like structure (not just column database name and values).
     */
    generatedMaps: ObjectLiteral[];
}```

**Comment by GQDeltex** [comment]
That's what I was thinking. Check the rows affected and return an error (or null idk) if `?affected` == 0, else findOneBy on the ID to get the updated data.

**Review by Yuerino — APPROVED** [review]
LGTM

**Pull request merged**
